version: '3.8'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3000:3000"
    environment:
      - SERVICE_FQDN_CLIENT_3000
      - NODE_ENV=production
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "4000:4000"
    environment:
      - SERVICE_FQDN_CLIENT_3000
      - NODE_ENV=production
