version: '3.8'

services:
  front:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: nuxt-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - back

  back:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
